name: nevesomiy
description: Poetry mobile application.

publish_to: 'none' 

version: 1.1.3+5

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # ui
  confetti: ^0.7.0
  loading_animation_widget: ^1.2.0+4
  flutter_svg: ^2.0.7
  liquid_pull_to_refresh: ^3.0.1
  
  # fireBase and notifier
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  firebase_messaging: ^14.9.3 
  # firebase_in_app_messaging: ^0.7.5+6
  cloud_firestore: ^4.17.4 

  # bl
  intl: ^0.19.0
  email_validator: ^2.1.17
  dartx: ^1.2.0
  connectivity_plus: ^6.0.3
  go_router: ^14.1.3
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  bloc: ^8.1.2 
  shared_preferences: ^2.2.1
  mask_text_input_formatter: ^2.5.0
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/


  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf 

